from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),

    # bsc 
    path('bsc/list_token/', views.list_token, name='list_token'),
    path('exchange/bsc/tokens/<str:symbol>/', views.tokens, name='tokens'),
    path('exchange/bsc/place_buy_order/', views.place_buy_order, name='place_buy_order'),
    path('exchange/bsc/place_sell_order/', views.place_sell_order, name='place_sell_order'),
    path('bsc/new_order_id/', views.new_order_id, name='new_order_id'),
    path('bsc/order_book/<str:address_>/<str:url_slug_>/', views.order_book, name='order_book'),
    path('bsc/order_history/<str:address_>/<str:url_slug_>/<str:address>/', views.order_history, name='order_history'),
    path('bsc/recent_trades/<str:address_>/', views.recent_trades, name='recent_trades'),
    path('bsc/check_sell_orders/<str:address_>/<str:price>/', views.check_sell_order, name='check_sell_order'),
    path('bsc/check_buy_orders/<str:address_>/<str:price>/', views.check_buy_order, name='check_buy_order'),
    path('bsc/get_market_sell/<str:address_>/', views.get_market_sell, name='get_market_sell'),
    path('bsc/get_market_buy/<str:address_>/', views.get_market_buy, name='get_market_buy'),
    path('bsc/get_max_buy_price/<str:token>/', views.get_max_buy_price, name='get_max_buy_price'),
    path('exchange/bsc/<str:address_>/<str:url_slug_>/', views.home, name='home'),
    path('exchange/bsc/revoke_sell_order', views.revoke_sell_order, name='revoke_sell_order'),
    path('exchange/bsc/revoke_buy_order', views.revoke_buy_order, name='revoke_buy_order'),
    path('exchange/bsc/', views.exchange, name='exchange'),
    path('bsc/api/get_data/<str:address_>/', views.chart, name='chart'),
    path('bsc/chart/', views.play_chart, name='play_chart'),
    # path('exchange/bsc/control/', views.control, name='control'),
    path('bsc/api/number_of_listed_tokens/<str:address_>/', views.number_of_listed_tokens, name='number_of_listed_tokens'),
    path('exchange/bsc/all_listed_tokens/', views.all_listed_tokens, name='all_listed_tokens'),
    path('exchange/bsc/market_maker/', views.market_maker, name='market_maker'),
    path('bsc/auto_market_maker/<str:token>/', views.auto_market_maker, name='auto_market_maker'),
    path('bsc/day_volumes/<str:address>/', views.day_volumes, name='day_volumes'),

    #polygon
    path('polygon/list_token/', views.polygon_list_token, name='list_token'),
    path('exchange/polygon/tokens/<str:symbol>/', views.polygon_tokens, name='tokens'),
    path('exchange/polygon/place_buy_order/', views.polygon_place_buy_order, name='place_buy_order'),
    path('exchange/polygon/place_sell_order/', views.polygon_place_sell_order, name='place_sell_order'),
    path('polygon/new_order_id/', views.polygon_new_order_id, name='new_order_id'),
    path('polygon/order_book/<str:address_>/<str:url_slug_>/', views.polygon_order_book, name='order_book'),
    path('polygon/order_history/<str:address_>/<str:url_slug_>/<str:address>/', views.polygon_order_history, name='order_history'),
    path('polygon/recent_trades/<str:address_>/', views.polygon_recent_trades, name='recent_trades'),
    path('polygon/check_sell_orders/<str:address_>/<str:price>/', views.polygon_check_sell_order, name='check_sell_order'),
    path('polygon/check_buy_orders/<str:address_>/<str:price>/', views.polygon_check_buy_order, name='check_buy_order'),
    path('polygon/get_market_sell/<str:address_>/', views.polygon_get_market_sell, name='get_market_sell'),
    path('polygon/get_market_buy/<str:address_>/', views.polygon_get_market_buy, name='get_market_buy'),
    path('polygon/get_max_buy_price/<str:token>/', views.polygon_get_max_buy_price, name='get_max_buy_price'),
    path('exchange/polygon/<str:address_>/<str:url_slug_>/', views.polygon_home, name='home'),
    path('exchange/polygon/revoke_sell_order', views.polygon_revoke_sell_order, name='revoke_sell_order'),
    path('exchange/polygon/revoke_buy_order', views.polygon_revoke_buy_order, name='revoke_buy_order'),
    path('exchange/polygon/', views.polygon_exchange, name='exchange'),
    path('polygon/api/get_data/<str:address_>/', views.polygon_chart, name='chart'),
    path('polygon/chart/', views.polygon_play_chart, name='play_chart'),
    # path('exchange/polygon/control/', views.polygon_control, name='control'),
    path('polygon/api/number_of_listed_tokens/<str:address_>/', views.polygon_number_of_listed_tokens, name='number_of_listed_tokens'),
    path('exchange/polygon/all_listed_tokens/', views.polygon_all_listed_tokens, name='all_listed_tokens'),
    path('exchange/polygon/market_maker/', views.polygon_market_maker, name='market_maker'),
    path('polygon/auto_market_maker/<str:token>/', views.polygon_auto_market_maker),
    path('polygon/day_volumes/<str:address>/', views.polygon_day_volumes, name='day_volumes'),

     #ethereum
    path('ethereum/list_token/', views.ethereum_list_token, name='list_token'),
    path('exchange/ethereum/tokens/<str:symbol>/', views.ethereum_tokens, name='tokens'),
    path('exchange/ethereum/place_buy_order/', views.ethereum_place_buy_order, name='place_buy_order'),
    path('exchange/ethereum/place_sell_order/', views.ethereum_place_sell_order, name='place_sell_order'),
    path('ethereum/new_order_id/', views.ethereum_new_order_id, name='new_order_id'),
    path('ethereum/order_book/<str:address_>/<str:url_slug_>/', views.ethereum_order_book, name='order_book'),
    path('ethereum/order_history/<str:address_>/<str:url_slug_>/<str:address>/', views.ethereum_order_history, name='order_history'),
    path('ethereum/recent_trades/<str:address_>/', views.ethereum_recent_trades, name='recent_trades'),
    path('ethereum/check_sell_orders/<str:address_>/<str:price>/', views.ethereum_check_sell_order, name='check_sell_order'),
    path('ethereum/check_buy_orders/<str:address_>/<str:price>/', views.ethereum_check_buy_order, name='check_buy_order'),
    path('ethereum/get_market_sell/<str:address_>/', views.ethereum_get_market_sell, name='get_market_sell'),
    path('ethereum/get_market_buy/<str:address_>/', views.ethereum_get_market_buy, name='get_market_buy'),
    path('ethereum/get_max_buy_price/<str:token>/', views.ethereum_get_max_buy_price, name='get_max_buy_price'),
    path('exchange/ethereum/<str:address_>/<str:url_slug_>/', views.ethereum_home, name='home'),
    path('exchange/ethereum/revoke_sell_order', views.ethereum_revoke_sell_order, name='revoke_sell_order'),
    path('exchange/ethereum/revoke_buy_order', views.ethereum_revoke_buy_order, name='revoke_buy_order'),
    path('exchange/ethereum/', views.ethereum_exchange, name='exchange'),
    path('ethereum/api/get_data/<str:address_>/', views.ethereum_chart, name='chart'),
    path('ethereum/chart/', views.ethereum_play_chart, name='play_chart'),
    # path('exchange/ethereum/control/', views.ethereum_control, name='control'),
    path('ethereum/api/number_of_listed_tokens/<str:address_>/', views.ethereum_number_of_listed_tokens, name='number_of_listed_tokens'),
    path('exchange/ethereum/all_listed_tokens/', views.ethereum_all_listed_tokens, name='all_listed_tokens'),
    path('exchange/ethereum/market_maker/', views.ethereum_market_maker, name='market_maker'),
    path('ethereum/auto_market_maker/<str:token>/', views.ethereum_auto_market_maker),
    path('ethereum/day_volumes/<str:address>/', views.ethereum_day_volumes, name='day_volumes'),


    # API Endpoints
    path('fetch_currency_price/<str:symbol>/', views.fetch_currency_price, name="fetch_currency_price"),
    path('exchange/api/pairs/', views.pairs, name='pairs'),
    path('exchange/api/tickers/', views.tickers, name='tickers'),
    path('exchange/api/orderbook/', views.orderbook, name='orderbook'),
    path('exchange/api/historical_trades/', views.historical_trades, name='historical_trades'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

